Traceback (most recent call last):
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Python/3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay



dt = DecisionTreeClassifier(class_weight='balanced',
                             max_leaf_nodes=13)
dt.fit(X_train_80_enc,y_train_80)

train_acc = accuracy_score(y_true=y_train_80, y_pred=dt.predict(X_train_80_enc))
test_acc  = accuracy_score(y_true=y_test,  y_pred=dt.predict(X_test_enc))

print ("Train Acc: {:.3f}".format(train_acc) )
print ("Test Acc : {:.3f}".format(test_acc) )

class_rep = classification_report(y_true=y_test, y_pred=dt.predict(X_test_enc),
                                 target_names=label_enc.classes_)
print (class_rep)


ConfusionMatrixDisplay.from_estimator(
    estimator=dt,
    X=X_test_enc, y=y_test,
    cmap = 'Blues_r');

------------------

----- stdout -----
Train Acc: 0.994
Test Acc : 0.989
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[57], line 15[0m
[1;32m     12[0m [38;5;28mprint[39m ([38;5;124m"[39m[38;5;124mTrain Acc: [39m[38;5;132;01m{:.3f}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(train_acc) )
[1;32m     13[0m [38;5;28mprint[39m ([38;5;124m"[39m[38;5;124mTest Acc : [39m[38;5;132;01m{:.3f}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(test_acc) )
[0;32m---> 15[0m class_rep [38;5;241m=[39m [43mclassification_report[49m[43m([49m[43my_true[49m[38;5;241;43m=[39;49m[43my_test[49m[43m,[49m[43m [49m[43my_pred[49m[38;5;241;43m=[39;49m[43mdt[49m[38;5;241;43m.[39;49m[43mpredict[49m[43m([49m[43mX_test_enc[49m[43m)[49m[43m,[49m
[1;32m     16[0m [43m                                 [49m[43mtarget_names[49m[38;5;241;43m=[39;49m[43mlabel_enc[49m[38;5;241;43m.[39;49m[43mclasses_[49m[43m)[49m
[1;32m     17[0m [38;5;28mprint[39m (class_rep)
[1;32m     20[0m ConfusionMatrixDisplay[38;5;241m.[39mfrom_estimator(
[1;32m     21[0m     estimator[38;5;241m=[39mdt,
[1;32m     22[0m     X[38;5;241m=[39mX_test_enc, y[38;5;241m=[39my_test,
[1;32m     23[0m     cmap [38;5;241m=[39m [38;5;124m'[39m[38;5;124mBlues_r[39m[38;5;124m'[39m);

File [0;32m/Library/Python/3.9/site-packages/sklearn/utils/_param_validation.py:211[0m, in [0;36mvalidate_params.<locals>.decorator.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    205[0m [38;5;28;01mtry[39;00m:
[1;32m    206[0m     [38;5;28;01mwith[39;00m config_context(
[1;32m    207[0m         skip_parameter_validation[38;5;241m=[39m(
[1;32m    208[0m             prefer_skip_nested_validation [38;5;129;01mor[39;00m global_skip_validation
[1;32m    209[0m         )
[1;32m    210[0m     ):
[0;32m--> 211[0m         [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    212[0m [38;5;28;01mexcept[39;00m InvalidParameterError [38;5;28;01mas[39;00m e:
[1;32m    213[0m     [38;5;66;03m# When the function is just a wrapper around an estimator, we allow[39;00m
[1;32m    214[0m     [38;5;66;03m# the function to delegate validation to the estimator, but we replace[39;00m
[1;32m    215[0m     [38;5;66;03m# the name of the estimator by the name of the function in the error[39;00m
[1;32m    216[0m     [38;5;66;03m# message to avoid confusion.[39;00m
[1;32m    217[0m     msg [38;5;241m=[39m re[38;5;241m.[39msub(
[1;32m    218[0m         [38;5;124mr[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;124m\[39m[38;5;124mw+ must be[39m[38;5;124m"[39m,
[1;32m    219[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mparameter of [39m[38;5;132;01m{[39;00mfunc[38;5;241m.[39m[38;5;18m__qualname__[39m[38;5;132;01m}[39;00m[38;5;124m must be[39m[38;5;124m"[39m,
[1;32m    220[0m         [38;5;28mstr[39m(e),
[1;32m    221[0m     )

File [0;32m/Library/Python/3.9/site-packages/sklearn/metrics/_classification.py:2561[0m, in [0;36mclassification_report[0;34m(y_true, y_pred, labels, target_names, sample_weight, digits, output_dict, zero_division)[0m
[1;32m   2555[0m         warnings[38;5;241m.[39mwarn(
[1;32m   2556[0m             [38;5;124m"[39m[38;5;124mlabels size, [39m[38;5;132;01m{0}[39;00m[38;5;124m, does not match size of target_names, [39m[38;5;132;01m{1}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(
[1;32m   2557[0m                 [38;5;28mlen[39m(labels), [38;5;28mlen[39m(target_names)
[1;32m   2558[0m             )
[1;32m   2559[0m         )
[1;32m   2560[0m     [38;5;28;01melse[39;00m:
[0;32m-> 2561[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   2562[0m             [38;5;124m"[39m[38;5;124mNumber of classes, [39m[38;5;132;01m{0}[39;00m[38;5;124m, does not match size of [39m[38;5;124m"[39m
[1;32m   2563[0m             [38;5;124m"[39m[38;5;124mtarget_names, [39m[38;5;132;01m{1}[39;00m[38;5;124m. Try specifying the labels [39m[38;5;124m"[39m
[1;32m   2564[0m             [38;5;124m"[39m[38;5;124mparameter[39m[38;5;124m"[39m[38;5;241m.[39mformat([38;5;28mlen[39m(labels), [38;5;28mlen[39m(target_names))
[1;32m   2565[0m         )
[1;32m   2566[0m [38;5;28;01mif[39;00m target_names [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   2567[0m     target_names [38;5;241m=[39m [[38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m l [38;5;28;01mfor[39;00m l [38;5;129;01min[39;00m labels]

[0;31mValueError[0m: Number of classes, 3, does not match size of target_names, 4. Try specifying the labels parameter

