Traceback (most recent call last):
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Python/3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/andreramolivaz/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import numpy as np

# convert form prediction to id
y_pred = model.predict(train_images)
y_pred = np.argmax(y_pred, axis=1) # argmax along axis 1

# convert from on-hot to original 
# (we could take the original)
y_true = np.argmax(train_labels, axis=1) # argmax along axis 1

# compute classification report
print ("Classification Report")
print ( classification_report(y_true, y_pred) )

# compute confusion matrix
mat = confusion_matrix(y_true, y_pred)

fig, axes = plt.subplots(figsize=(6,6), tight_layout=True)
sns.heatmap(mat, square=True, annot=True, fmt='d', 
            cbar=False, cmap="Blues")
axes.set_xlabel('Predicted Label');
axes.set_ylabel('True Label')
axes.set_title('Confusion Matrix');
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[31], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m [38;5;28;01mimport[39;00m confusion_matrix, classification_report
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      5[0m [38;5;66;03m# convert form prediction to id[39;00m

[0;31mModuleNotFoundError[0m: No module named 'seaborn'

